### ISSUE TITLE
Strange behaviour on capture from same virtual machine

### ISSUE THREAD

**Issue by danielmartinezruiz** [zaleos/sipplauncher#12]
## Description

- Currently, when we execute a test-sipp normal scenario, we expect that UA0 and UA1 communicate through our products, not directly.
- If it is executed on the same virtual machine, there are communications between UA0 and UA1.
- SIP flow image example:
<img width="763" alt="Screenshot 2019-12-16 at 11 51 30" src="https://user-images.githubusercontent.com/13116933/70901096-641b0980-1ffa-11ea-9479-bfebbcef4107.png">

- If it is executed on a different virtual machine, the SIP flow is correct (see acceptance criteria)

## Acceptance criteria

- SIP flow is shown correctly as this image:
<img width="752" alt="Screenshot 2019-12-16 at 11 59 24" src="https://user-images.githubusercontent.com/13116933/70901649-7ba6c200-1ffb-11ea-8f10-9ab8579b7338.png">

**Comment by pcapdump** [comment]
Hi, Daniel!
Please attach whole content of /var/tmp/sipplauncher/... test folder  (in which .pcap file is located).

**Comment by danielmartinezruiz** [comment]
Here it is. This is not the same capture than above (different ips and ports) but the behavior is the same.

[normal-0000.zip](https://github.com/zaleos/sipplauncher/files/3974139/normal-0000.zip)

**Comment by pcapdump** [comment]
According to Danny, all apps are running on the same VM.
My assumption is that server TLS port is bound to 0.0.0.0 and not to 10.22.22.200.
This makes it possible to take any of local addresses when making outbound call, and it chooses 10.22.22.61.
So likely pcap shows what really happens inside VM.

**Comment by NGSegovia** [comment]
> I have an assumption, that server app doesn't do socket.bind(10.22.22.200) before doing socket.connect() for outbound call.
I don't think so, I think ip address will be bind on application start.
@danielmartinezruiz can you confirm the same problem can be reproduced with other products?

**Comment by NGSegovia** [comment]
Based on our conversation this seems not to be an issue in Sipplauncher. @pcapdump I'll close it.
