### ISSUE TITLE
chdir when executing before.sh/after.sh

### ISSUE THREAD

**Issue by NGSegovia** [zaleos/sipplauncher#4]
## Description

This change to sipplauncher seems to be necessary when migrating to minimal provisioning tests, which need this logic:

Read and save some global config options 
Alter these global config options
Run sipp
Restore back global config options which were in before the test.

Here is the initial issue:
https://gitlab.com/zaleos/softza/inesrp-sipp-dry/issues/11

We need this feature in case if a test case requires changing some global option in DUT.

## Proposed logic
Above logic could be implemented via saving config options into temporary file in test run tmp folder.
And restoring back these config options from tmp file after test is finished.
For this to work, it'd better if sipplaucher changed current working dir to test run tmp folder when executing before.sh/after.sh.
So that these scripts could easely write/read temp files in test tmp folder.
Before.sh and after.sh will be responsible for reading, saving and restoring global options.
##  Subtasks

Implement feature in sipplaucher
Implement unit-tests which will save some file content in file test folder, and check the file content validity

## Acceptance Criteria

Manual testing: save to temp file from before.sh, read and echo from the temp file in after.sh
Unit tests mentioned above should pass

**Comment by pcapdump** [comment]
Need to move before/after script running out from SIPpTest.run():

1) either to PysippProcess - then before/after scripts could be run concurrently if --group cmd arg is used
2) or to SIPpTest.pre_run()/SIPpTest.post_run() - then before/after scripts will be always run consecutively with respect to each other.

If we leave before/after script running where they are now (in SIPpTest.run()), then on chdir() we'll get a race condition when running sipplauncher with --group arg: several threads wil concurrently chdir()

**Comment by pcapdump** [comment]
> Need to move before/after script running out from SIPpTest.run():
> 
> 1. either to PysippProcess - then before/after scripts could be run concurrently if --group cmd arg is used
> 2. or to SIPpTest.pre_run()/SIPpTest.post_run() - then before/after scripts will be always run consecutively with respect to each other.
> 
> Otherwise on adding chdir() to SIPpTest.__run_script(), we'll introduce a race condition when running sipplauncher with --group arg: several threads will concurrently call chdir() and change WD for whole process.
> 
> Option 1 is more close to what we currently have.

However if used Option 1, we'll get another race condition.
Say, 2 have TestA and TestB running concurrently.

1. TestA reads some global config option ValueOrig from DUT and saves it to tmp run dir.
2. TestA sets new value for option - ValueA - in DUT
3. TestA runs SIPp
4. TestB read same global config option - ValueA and saves it to tmp run dir.
5. TestB sets new value for option - ValueB
6. TestB runs SIPp
7. TestA SIPp finishes.
8. TestA restores ValueOrig into DUT.
9. TestB SIPp finishes.
10. TestB restores ValueA into thus.

Thus, after running this 2 tests option value in DUT has been changed ValueOrig -> ValueA.
However, it should be restored to ValueOrig!

Thus, we need to follow Option 2 approach - run all before/after scrips consecutively for all tests from the test group.

**Comment by NGSegovia** [comment]
Hi @pcapdump ,

can you clarify which would be the final order using option 2?

**Comment by pcapdump** [comment]
> Hi @pcapdump ,
> 
> can you clarify which would be the final order using option 2?

1. TestA reads some global config option ValueOrig from DUT and saves it to tmp run dir.
2. TestA sets new value for option - ValueA - in DUT
3. TestB reads same global config option - ValueA and saves it to tmp run dir.
4. TestB sets new value for option - ValueB
5. TestA runs SIPp
6. TestB runs SIPp
7. TestB SIPp finishes
8. TestA SIPp finishes.
9. TestB restores ValueA into DUT.
10. TestA restores ValueOrig into DUT.

**Comment by NGSegovia** [comment]
Ok @pcapdump , this is asuming (in fact in both options) that TestA and TestB configuration is compatible right (not collisions)? Because if not TestA would fail. I'm ok with this option, correct me if I'm wrong but this is in esence:

1. Save global state
2. Run all provisions (before.sh)
3. Run sipp's (concurrently)
4. Run all provisions (after.sh) 
5. Return global state

**Comment by pcapdump** [comment]
> Ok @pcapdump , this is asuming (in fact in both options) that TestA and TestB configuration is compatible right (not collisions)? Because if not TestA would fail.

Yes.
if both tests require different values for the same global option, they we'll fail if they are run concurrently.
They could be run only consecutively in this case.

> I'm ok with this option, correct me if I'm wrong but this is in esence:
> 
> 1. Save global state
> 2. Run all provisions (before.sh)
> 3. Run sipp's (concurrently)
> 4. Run all provisions (after.sh)
> 5. Return global state

yes, Nacho, you're correct
