### ISSUE TITLE
Remove manual "sslkeylog.c" magic

### ISSUE THREAD

**Issue by luismartingil** [zaleos/sipplauncher#7]
## Description
- Currently, passing sslkeylog.c (and compiling it) is creating some issues when deploying the project to pypi.
- There is a very interesting pip project that is solving this problem already https://pypi.org/project/sslkeylog/
https://github.com/segevfiner/sslkeylog

## Acceptance criteria

1.  Use Python dependency and remove manual "sslkeylog.c" magic.

**Comment by pcapdump** [comment]
I could give it a try, but it would be a surprise for me if this works.
Because actually we use sslkeylog.so to add a hook to `sipp` SSL exchange.
And not to sipplauncher's Python SSL exchange (because actually sipplauncher doesn't communicate via SSL to anybody - it launches sipp which does the SSL exchange).

**Comment by luismartingil** [comment]
Understood

**Comment by pcapdump** [comment]
Tried this: https://github.com/zaleos/sipplauncher/pull/11/files

But, as I expected, it doesn't work.

sslkeylog.txt is created, but it's empty.

Luis, what is the initial problem with sslkeylog.c and pypi?

**Comment by NGSegovia** [comment]
Hi @pcapdump ,

The main problem is that installing from pypi is not running our "make install" which is compiling on the fly mentioned .c file. So we can't install directly from pypi. https://github.com/zaleos/softza-sipplauncher/blob/1a5e863bb92fbbb6ad79a2608c53ceb89f954fa0/Makefile#L79-L79

**Comment by luismartingil** [comment]
@pcapdump Agreed - at least we need to change this https://github.com/zaleos/sipplauncher/blob/ca1ddfb20c4ca6fb50d61a68d5cf2f1e50c7e596/sipplauncher/main.py#L49-L61

- Make "libsslkeylog.so" path optional based on the command-line argument - if arg is present use it reading the dynamic path.
- "tls_premaster_keys.txt" string must go to a _Defaults.py_ file. I would default it to be "tls_ libsslkeylog_premaster_keys.txt" to give more context on where this file is coming from.

**Comment by pcapdump** [comment]
>Make "libsslkeylog.so" path optional based on the command-line argument - if arg is present use it reading the dynamic path.

Luis, I agree the aproach.
But I propose to slighly change it:

If libsslkeylog.so is not found, we don't raise an exception, but display the message to the user: "libsslkeylog.so is not found. To dump SSL keys please install Sipplaucher from source".

Also we remove libsslkeylog.so from setup.py, and install libsslkeylog.so via Makefile.

This way, if user installs from pypi - he gets the above message on attempt to use TLS.
If user needs the mentioned feature - he follows the message hint, installs Sipplauncher from source and gets this feature.

>"tls_premaster_keys.txt" string must go to a Defaults.py file. I would default it to be "tls_ >libsslkeylog_premaster_keys.txt" to give more context on where this file is coming from.

Agree with this.

**Comment by luismartingil** [comment]
Like it - but logging warning not to be "please install sipplauncher from sources", but something similar to "library no found, please place this lib in ..."

**Comment by pcapdump** [comment]
> Like it - but logging warning not to be "please install sipplauncher from sources", but something similar to "library no found, please place this lib in ..."

OK!
